### ISSUE TITLE
Error running make site_test 

### ISSUE THREAD

**Issue by zhengyang4k** [youtube/vitess#109]
```
W1024 03:49:35.368687 09757 mysqld.go:190] assuming shutdown - no socket, no pid file
E1024 03:49:35.369195 09757 mysqld.go:418] error deleting dir /home/ubuntu/gopath/vtdataroot/vt_0000062344/data: lstat /home/ubuntu/gopath/vtdataroot/vt_0000062344/data: no such file or directory
E1024 03:49:35.369379 09757 mysqld.go:418] error deleting dir /home/ubuntu/gopath/vtdataroot/vt_0000062344/innodb: lstat /home/ubuntu/gopath/vtdataroot/vt_0000062344/innodb: no such file or directory
E1024 03:49:35.369397 09757 mysqld.go:418] error deleting dir /home/ubuntu/gopath/vtdataroot/vt_0000062344/relay-logs: lstat /home/ubuntu/gopath/vtdataroot/vt_0000062344/relay-logs: no such file or directory
E1024 03:49:35.369413 09757 mysqld.go:418] error deleting dir /home/ubuntu/gopath/vtdataroot/vt_0000062344/bin-logs: lstat /home/ubuntu/gopath/vtdataroot/vt_0000062344/bin-logs: no such file or directory
F1024 03:49:35.369426 09757 mysqlctl.go:238] failed teardown mysql (forced? true): lstat /home/ubuntu/gopath/vtdataroot/vt_0000062344/bin-logs: no such file or directory
goroutine 16 [running]:
github.com/golang/glog.stacks(0xc208027c00, 0x0, 0x0, 0x0)
	/home/ubuntu/gopath/src/github.com/golang/glog/glog.go:726 +0xcc
github.com/golang/glog.(*loggingT).output(0x1050e60, 0xc200000003, 0xc208046180)
	/home/ubuntu/gopath/src/github.com/golang/glog/glog.go:677 +0x243
github.com/golang/glog.(*loggingT).printf(0x1050e60, 0x3, 0x961890, 0x26, 0x2ad3a4ce3d58, 0x2, 0x2)
	/home/ubuntu/gopath/src/github.com/golang/glog/glog.go:635 +0x187
github.com/golang/glog.Fatalf(0x961890, 0x26, 0x2ad3a4ce3d58, 0x2, 0x2)
	/home/ubuntu/gopath/src/github.com/golang/glog/glog.go:1033 +0x64
main.teardownCmd(0xc208004480, 0xc2080044e0, 0xc20800e060, 0x1, 0x1)
	/home/ubuntu/gopath/src/github.com/youtube/vitess/go/cmd/mysqlctl/mysqlctl.go:238 +0x1ab
main.main()
	/home/ubuntu/gopath/src/github.com/youtube/vitess/go/cmd/mysqlctl/mysqlctl.go:324 +0x5e2
```

**Comment by enisoc** [comment]
Closing due to inactivity. Please reopen if needed.
