### ISSUE TITLE
grpc build problem

### ISSUE THREAD

**Issue by yfinkelstein** [youtube/vitess#1721]
While executing ./bootstrap.sh on OSX I get the following error:

```
[HOSTCXX] Compiling src/compiler/csharp_generator.cc
src/compiler/csharp_generator.cc:47:43: error: no member named 'GetReflectionClassName' in namespace 'google::protobuf::compiler::csharp'
using google::protobuf::compiler::csharp::GetReflectionClassName;
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
src/compiler/csharp_generator.cc:237:26: error: use of undeclared identifier 'GetReflectionClassName'
             "umbrella", GetReflectionClassName(service->file()), "index",
                         ^
2 errors generated.
make: *** [/Users/yfinkelstein/work/vitess_workspace/dist/grpc/grpc/objs/opt/src/compiler/csharp_generator.o] Error 1
ERROR: gRPC build failed
```

I'm following build setup instructions line by line as described in your "How to build".

**Comment by michael-berlin** [comment]
Hi Yuri,

Are you using the latest master branch from our Git repository?

If that's the case, I **guess** this problem is caused by another protobuf source installation which you have on your system.

The cause of your error is that the gRPC code is newer than the used protobuf library source code.

In practice this should not happen because gRPC also ships a matching protobuf version.

It should look like this on your disk:

`$VTROOT/dist/grpc/grpc`

=> should be a checkout of the gRPC Git branch "release-0_13_0"

`$VTROOT/dist/grpc/grpc/third_party/protobuf`

=> should be a checkout of the protobuf Git branch "v3.0.0-beta-2"

My guess is you have an older protobuf library on your system which gRPC is using instead of the shipped one in "third_party/protobuf".

**I can think of two solutions to fix your problem:**
a) hack gRPC to use the old API again. We had this hack in before but we no longer need it. The hack is here: https://github.com/youtube/vitess/commit/07ec6c95dadb17e7c22751e1bb80551bc9163f53

`sed -i -- 's/GetUmbrellaClassName/GetReflectionClassName/g' $VTROOT/dist/grpc/grpc/src/compiler/csharp_generator.cc`

is the command for the text replacement which reverts the gRPC code to the old API

b) find the protobuf library source code on your system which is used by gRPC and delete it. After that, gRPC should use the shipped library instead?

Some more notes:
- We don't need the C# gRPC code generator, but we just run a default install of gRPC and as part of that it must be compiled as well. 

Cheers,
Michael

**Comment by michael-berlin** [comment]
Clarification: 

Hack was added here: https://github.com/youtube/vitess/commit/5504ab1263e3de78a1632a138cd33acfb798b4e0
And removed here (since it should no longer be needed): https://github.com/youtube/vitess/commit/07ec6c95dadb17e7c22751e1bb80551bc9163f53

**Comment by yfinkelstein** [comment]
Hi Michael, 
appreciate you looking into it and quick response. You are indeed correct: I do have protobuf 3.0.0-beta1 distribution installed in my /usr/local  lib and bin back in Nov 2015. 

I will of course delete it as right now I don't need it. But I would suggest that a change to your script is to be made to prevent such cases. Basically as I understand it you need to inject the path to downloaded and built libraries under dist in front of DYLD_LIBRARY_PATH.

Thanks
Yuri

**Comment by yfinkelstein** [comment]
Additional info: after removing all libproto* under /usr/local/lib and restarting ./bootstrap.sh I got a different error: clang compiler reported that -lproto* point to non-existent libraries. This is because I forgot to do this:
```
rm /usr/local/lib/pkgconfig/protobuf*
```

This might be the root of the problem. Your script needs to tell pkg-config to look for specs under dist only. Then at least the build phase should complete normally. When running/debugging the apps that link with libproto system library path is probably already controlled.

**Comment by yfinkelstein** [comment]
After removal of pkg-config specs ./bootstrap.sh completes successfully, but somewhere in the middle I saw this:
```
We couldn't find protoc 3.0.0+ installed on your system. While this
won't prevent grpc from working, you won't be able to compile
and run any meaningful code with it.


Please download and install protobuf 3.0.0+ from:

   https://github.com/google/protobuf/releases

Once you've done so, or if you think this message is in error,
you can re-run this check by doing:

```

Is this expected?

**Comment by yfinkelstein** [comment]
Still not quite a success:

```
$ make build
Tue May 24 00:11:17 PDT 2016: Building source tree
# github.com/youtube/vitess/vendor/launchpad.net/gozk/zookeeper
In file included from vendor/launchpad.net/gozk/zookeeper/zk.go:15:
/Users/yfinkelstein/work/vitess_workspace/dist/vt-zookeeper-3.4.6/include/zookeeper/zookeeper.h:22:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
1 error generated.
# github.com/youtube/vitess/go/cgzip
go/cgzip/adler32.go:11:10: fatal error: 'zlib.h' file not found
#include "zlib.h"
         ^
1 error generated.
# github.com/youtube/vitess/go/mysql
go/mysql/mysql.go:11:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
1 error generated.
make: *** [build] Error 2

```

**Comment by yfinkelstein** [comment]
I have 
```
$ type gcc
gcc is /usr/bin/gcc

$ c++ --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


$ type clang
clang is hashed (/usr/local/opt/llvm/bin/clang)


```

**Comment by yfinkelstein** [comment]
stdlib.h exists in multiple places:
```
$ find /usr/ -name stdlib.h
/usr//local/Cellar/llvm/HEAD/include/c++/v1/stdlib.h



$ find /Applications/Xcode.app/ -name stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/c++/4.2.1/tr1/stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/c++/4.2.1/tr1/stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1/tr1/stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app//Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/stdlib.h
/Applications/Xcode.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/iPhoneOS.sdk/usr/include/stdlib.h
/Applications/Xcode.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/iPhoneSimulator.sdk/usr/include/stdlib.h
/Applications/Xcode.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/MacOSX.sdk/usr/include/stdlib.h

```

**Comment by yfinkelstein** [comment]
It works using gmake instead of make though ....

**Comment by michael-berlin** [comment]
yfinkelstein wrote:

> This might be the root of the problem. Your script needs to tell pkg-config to look for specs under dist only. Then at least the build phase should complete normally. When running/debugging the apps that link with libproto system library path is probably already controlled.

Unfortunately, it is not our script :) It's the Makefile from the gRPC project. I think the solution here is that they bump the minimum protobuf version which they require. Clearly, 3.0.0-beta1 doesn't work with the 0.13 release.

I've filed https://github.com/grpc/grpc/issues/6701 with them.

**Comment by michael-berlin** [comment]
yfinkelstein wrote:

> After removal of pkg-config specs ./bootstrap.sh completes successfully, but somewhere in the middle I > saw this:
> 
> We couldn't find protoc 3.0.0+ installed on your system. While this
> won't prevent grpc from working, you won't be able to compile
> and run any meaningful code with it.
> 
> 
> Please download and install protobuf 3.0.0+ from:
> 
>    https://github.com/google/protobuf/releases
> 
> Once you've done so, or if you think this message is in error,
> you can re-run this check by doing:
> 
> Is this expected?

Yes, this is expected. I get the same message on my system.

Only the return value of bootstrap.sh counts :) And that succeeded for you.

**Comment by michael-berlin** [comment]
> It works using gmake instead of make though ....

That's good to hear :)

Note that the compilation support for MacOSX is not officially supported. It was contributed by a user and we currently do not automatically test it e.g. in Travis CI.

Therefore, something might always break along the way and we'll do our best to fix things and happily accept contributions.

I'm wondering if the difference between gmake and make is related due to your specific setup and it would not occur on a clean MacOSX installation. If I remember correctly from my limited past experience on MacOSX, this is a common issue that "gmake" instead of "make" has to be used?

If you can think of specific actions how to fix this or improve our docs, let me know. Otherwise, I would consider your issue as fixed for now :)

**Comment by Rastusik** [comment]
Hi, @yfinkelstein, I'm the one who made the OSX integration walkthrough and some little build script changes. 

The integration is based on installing all secondary dependencies using Homebrew and wasn't tested on any different (and in your case quite special) OSX setups, only on my 2 macs (work and at home) and on a clean OSX setup. Maybe you could try to make some alterations, but the walkthrough should be working for the majority of users. I think a better option would be to debug your system and try to find what is specifically wrong and fix it. If the fix doesn't break anything in the walkthrough, it might be applicable into the build script, just make a pull request :)

**Comment by yfinkelstein** [comment]
@Rastusik - thanks for the fixes for osx. After removing non-homebrew installation of grpc
 I was able to build the code, but still - only with gmake. Regular make produced some odd error (above). Do you see anything else non-standard in my setup? LLVM compiler in /usr/local perhaps?

**Comment by yfinkelstein** [comment]
This is probably not related to osx, but ```gmake test``` fails in every test saying ZK server was not found.
I do have vmware fusion on this laptop and my hostname resolves this to a virtual interface IP rather than  eth0. This is OK for as long as both server and client bind to this IP. Is this the reason why ZK is not found? It bind's to a different IP? I can't fin the place where the server is started.

On the other hand, ```gmake site_test``` goes on much better and most tests complete successfully. Some do fail, but that's probably because it's a dev brunch.

Strangely   enough, when running ```make test``` in a base vitess docker container all test fails as well but with a different error: 
```
vitess@3fa57b9774b3:/vt/src/github.com/youtube/vitess$ more _test/local.20160524-212849.7553/vtgatev2-1.2.log
Traceback (most recent call last):
  File "test/vtgatev2_test.py", line 13, in <module>
    import environment
  File "/vt/src/github.com/youtube/vitess/test/environment.py", line 29, in <module>
    if os.environ['USER'] == 'root':
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'USER'
```

**Comment by Rastusik** [comment]
@yfinkelstein - regarding gmake - I'm not sure why normal make doesn't work for you, I think I'm using make packaged with Xcode 

regarding the tests - some of the tests fail on my setup too, but I think it is because  they need more resources than my laptop is able to provide (e.g. at least 6 simultaneously running mysql instances doing resharding)

I don't remember any problems with zoo keeper, but I ran everything on localhost, not in a VM. I had  some problems with my /etc/hosts file though (https://groups.google.com/forum/#!topic/vitess/AMVLXpi__HE - last two posts), but I'm not sure whether this is related to your problems.

Regarding your error message - it seems like you are running Vitess as root in the docker container, which is prohibited (at least I think so :) ) - try running as a non-privileged user.

**Comment by yfinkelstein** [comment]
I'm also not using VM for this - just the virtual network of vmware fusion. it make the IP stable as I move around various networks than cause eth0 IP to change.

re root, I don't think it's the case:
```
vitess@3fa57b9774b3:/vt/src/github.com/youtube/vitess$ whoami
vitess
```

**Comment by yfinkelstein** [comment]
@Rastusik The email thread you pointed to mentions exactly the error that I see:
```
  panic: no zk server found for host localhost in config 1@mfris-mbpro.local:16027:16028:16029
```

It looks like dual host name and IP is indeed the cause.

**Comment by Rastusik** [comment]
in that case just modify your /etc/hosts file to match your IP with your host name, in my case it was:

192.168.15.4    rasta.local rasta

where the IP is my LAN IP and hostname is my current hostname (or at my work computer it would be mfris-mbpro and mfris-mbpro.local)

Regarding the root user - it's mentioned in the error message you provided, are you sure with that?

```
if os.environ['USER'] == 'root':
```

Maybe you just have an environment variable with the value 'root' ? Also your hostname seems kind of weird to me.

**Comment by yfinkelstein** [comment]
>192.168.15.4 rasta.local rasta


Did just that - no effect

```
$ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
192.168.11.1    LM-SJL-11000508 LM-SJL-11000508.local
```

They indeed were resolving to different IPs before but not anymore. The test still fail with the same error

Re the error inside the docker base container, I'm not doing anything special. Just do
```
docker run --rm -it vitess/base bash
```
That's why the host name shown there is a transient string. How can this result in something different then what others see?

**Comment by yfinkelstein** [comment]
On mac, here is what the error comes down to:

```
$ /Users/yfinkelstein/work/vitess_workspace/bin/zkctl -log_dir /Users/yfinkelstein/work/vitess_workspace/vtdataroot/vt_266856033/tmp -zk.cfg 1@lm-sjl-11000508.local:17806:17807:17808 init
panic: no zk server found for host LM-SJL-11000508 in config 1@lm-sjl-11000508.local:17806:17807:17808 [recovered]
	panic: no zk server found for host LM-SJL-11000508 in config 1@lm-sjl-11000508.local:17806:17807:17808

goroutine 1 [running]:
panic(0x4247860, 0xc820014a30)
	/usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
github.com/youtube/vitess/go/exit.doRecover(0x4247860, 0xc820014a30, 0xc820014a00)
	/Users/yfinkelstein/work/vitess_workspace/src/github.com/youtube/vitess/go/exit/exit.go:80 +0x2c2
github.com/youtube/vitess/go/exit.Recover()
	/Users/yfinkelstein/work/vitess_workspace/src/github.com/youtube/vitess/go/exit/exit.go:57 +0x48
panic(0x4247860, 0xc820014a30)
	/usr/local/opt/go/libexec/src/runtime/panic.go:443 +0x4e9
github.com/youtube/vitess/go/zk/zkctl.MakeZkConfigFromString(0x7fff5fbfefb3, 0x29, 0xc800000000, 0xc820053eb0)
	/Users/yfinkelstein/work/vitess_workspace/src/github.com/youtube/vitess/go/zk/zkctl/zkconf.go:176 +0x8ae
main.main()
	/Users/yfinkelstein/work/vitess_workspace/src/github.com/youtube/vitess/go/cmd/zkctl/zkctl.go:68 +0x11f

```

**Comment by yfinkelstein** [comment]
I figured that with parameter ```-zk.myid 1```  zkctl starts normally:
```
/Users/yfinkelstein/work/vitess_workspace/bin/zkctl -log_dir /Users/yfinkelstein/work/vitess_workspace/vtdataroot/vt_266856033/tmp -zk.cfg 1@lm-sjl-11000508:17806:17807:17808 -zk.myid 1 start
```

And now I see zk server running
```
110003290  9280  9275   0  4:04PM ttys000    0:00.54 /usr/bin/java -server -DZOO_LOG_DIR=/Users/yfinkelstein/work/vitess_workspace/vtdataroot/zk_001/logs -cp /Users/yfinkelstein/work/vitess_workspace/dist/vt-zookeeper-3.4.6/lib/zookeeper-3.4.6-fatjar.jar:/usr/local/lib/zookeeper-3.4.6-fatjar.jar:/usr/share/java/zookeeper-3.4.6.jar org.apache.zookeeper.server.quorum.QuorumPeerMain /Users/yfinkelstein/work/vitess_workspace/vtdataroot/zk_001/zoo.cfg

```

**Comment by michael-berlin** [comment]
yfinkelstein wrote:

> Strangely enough, when running make test in a base vitess docker container all tests fails as well but > with a different error:
> 
> vitess@3fa57b9774b3:/vt/src/github.com/youtube/vitess$ more _test/local.20160524-> 212849.7553/vtgatev2-1.2.log
> Traceback (most recent call last):
>   File "test/vtgatev2_test.py", line 13, in <module>
>     import environment
>   File "/vt/src/github.com/youtube/vitess/test/environment.py", line 29, in <module>
>     if os.environ['USER'] == 'root':
>   File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
>     raise KeyError(key)
> KeyError: 'USER'

KeyError suggests that the "USER" environment variable is not set at all.

Try to add "-e USER=vitess" to your "docker run" command.

Also make sure that you have a recent Docker version installed. 1.7.1 works fine on my system.

For example, I run tests within a Docker image as follows:
```sh
$ go run test.go
```

In general, note that tests are definitely not fully supported for MacOSX and never will be. You wouldn't run a Vitess production instance on a MacOSX system. You would always do that on a Linux system.

Instead, the idea behind the MacOSX support is to easily change Vitess code and test it with your application e.g. write an e2e test which launches Vitess and then your app uses it.

**Comment by yfinkelstein** [comment]
@michael-berlin 
>-e USER=vitess
Bingo, that was it. This nuance  is not mentioned in your docs anywhere. it might helps others to avoid the same issue

**Comment by yfinkelstein** [comment]
>tests are definitely not fully supported for MacOSX and never will be. 

Understand. But the issue with ZK is not the kind of problem why the tests are failing. I believe I found that with ```-zk.myid 1``` zkctl starts fine and without it - exits. This might be a bug as there is only 1 host name in the list of zk cluster members

**Comment by Rastusik** [comment]
There should be 3 zk instances running, if you are testing the local example.

**Comment by enisoc** [comment]
Closing due to inactivity. Feel free to reopen if you still have this issue.
