### ISSUE TITLE
Nil pointer dereference in WatchSrvVSchema

### ISSUE THREAD

**Issue by enisoc** [youtube/vitess#1909]
A user reported the following crash. It looks like the etcd watch can send `nil` in some conditions, so we need to handle that.

We probably need to fix it for `WatchSrvKeyspace` as well.

https://github.com/youtube/vitess/blob/master/go/vt/etcdtopo/serving_graph.go#L100
https://github.com/youtube/vitess/blob/master/go/vt/etcdtopo/serving_graph.go#L231

```
E0802 07:48:18.218090    3687 resilient_srv_topo_server.go:204] GetSrvKeyspaceNames(context.Backgroun
d.WithDeadline(2016-08-02 07:48:20.202757794 +0000 UTC [1.984653064s]), test) failed: Get http://192.
168.0.39:2371/v2/keys/vt/ns?quorum=true&recursive=false&sorted=true: dial tcp 192.168.0.39:2371: gets
ockopt: connection refused (no cached value, caching and returning error)
E0802 07:48:18.218518    3687 discoverygateway.go:120] Error when waiting for tablets: Get http://192
.168.0.39:2371/v2/keys/vt/ns?quorum=true&recursive=false&sorted=true: dial tcp 192.168.0.39:2371: get
sockopt: connection refused
E0802 07:48:18.218550    3687 discoverygateway.go:98] createDiscoveryGateway: Get http://192.168.0.39
:2371/v2/keys/vt/ns?quorum=true&recursive=false&sorted=true: dial tcp 192.168.0.39:2371: getsockopt: 
connection refused
W0802 07:48:18.219012    3687 planner.go:128] Got an empty vschema for cell test
E0802 07:48:18.219064    3687 serving_graph.go:212] Watch on /vt/ns/_VSchema failed, waiting for 30s 
to retry: Get http://192.168.0.39:2371/v2/keys/vt/ns/_VSchema?wait=true&waitIndex=1: dial tcp 192.168
.0.39:2371: getsockopt: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x4a7113]

goroutine 50 [running]:
github.com/youtube/vitess/go/vt/etcdtopo.(*Server).WatchSrvVSchema.func2(0xc8200a4960, 0xc820155d00, 
0xf, 0xc8200a4900, 0x7fcef4e35fa0, 0xc82000d0b0, 0xc8200a49c0)
        /vt/src/github.com/youtube/vitess/go/vt/etcdtopo/serving_graph.go:232 +0xe3
created by github.com/youtube/vitess/go/vt/etcdtopo.(*Server).WatchSrvVSchema
        /vt/src/github.com/youtube/vitess/go/vt/etcdtopo/serving_graph.go:246 +0x2cb
```

**Comment by enisoc** [comment]
This should be fixed by https://github.com/youtube/vitess/pull/1967.
