### ISSUE TITLE
BUG: vtgate tablet healthchecks silently fail when grpc connection fails

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2761]
I recently converted to all SSL connections, and in doing that I introduced a minor misconfiguration. The way this manifested was that my vtgates did not register any tablets as SERVING. This is what it looked like:

![screen shot 2017-04-11 at 1 23 15 pm](https://cloud.githubusercontent.com/assets/116591/24928705/52fcc670-1ed1-11e7-9b19-cb951d45ff6a.png)

Despite the tablet showing itself as healthy:
![screen shot 2017-04-11 at 1 24 03 pm](https://cloud.githubusercontent.com/assets/116591/24928714/5d619078-1ed1-11e7-8f60-5cec58a7f845.png)

There were no logs or anything to indicate an issue. The only log outputted was `Timeout waiting for all keyspaces / shards to have healthy tablets, may be in degraded mode` at startup.

Looking at the goroutine dumps in the debug profile I noticed that it seemed to be stuck in grpc.DialContext. I spent some time thinking the timeouts were off, before finally adding more logging to the code path.  Once I did I noticed this:

```
I0411 20:07:13.690825      17 conn.go:70] Trying to dial 'foo:16101' with opts [0x7927b0 0x792790 0x792960]
E0411 20:07:13.695277      17 conn.go:73] Got an error: x509: certificate is valid for bar.example.com, not foo.example.com
goroutine 243 [running]:
github.com/youtube/vitess/vendor/github.com/golang/glog.stacks(0x11c6100, 0x101398d, 0x7, 0x49)
	/usr/share/hubspot/jenkins-home/workspace/vitess-rpm/vitess-build/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:769 +0xa7
github.com/youtube/vitess/vendor/github.com/golang/glog.(*loggingT).output(0x11c6100, 0xc400000002, 0xc4201d34a0, 0x101398d, 0x7, 0x49, 0x0)
	/usr/share/hubspot/jenkins-home/workspace/vitess-rpm/vitess-build/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:675 +0x6fc
github.com/youtube/vitess/vendor/github.com/golang/glog.(*loggingT).printf(0x11c6100, 0xc400000002, 0xc61aa5, 0x10, 0xc420dd9db8, 0x1, 0x1)
	/usr/share/hubspot/jenkins-home/workspace/vitess-rpm/vitess-build/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:655 +0x14f
github.com/youtube/vitess/vendor/github.com/golang/glog.Errorf(0xc61aa5, 0x10, 0xc420dd9db8, 0x1, 0x1)
	/usr/share/hubspot/jenkins-home/workspace/vitess-rpm/vitess-build/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:1121 +0x67
github.com/youtube/vitess/go/vt/vttablet/grpctabletconn.DialTablet(0xc420176280, 0xb2d05e00, 0x2, 0xc420dd9fa8, 0x2, 0xc420dd9ed0)
	/usr/share/hubspot/jenkins-home/workspace/vitess-rpm/vitess-build/src/github.com/youtube/vitess/go/vt/vttablet/grpctabletconn/conn.go:73 +0x392
github.com/youtube/vitess/go/vt/discovery.(*healthCheckConn).stream(0xc4201d2840, 0xc42022c280, 0xc4210f2e20, 0x102d201, 0xc4210f2de0)
	/usr/share/hubspot/jenkins-home/workspace/vitess-rpm/vitess-build/src/github.com/youtube/vitess/go/vt/discovery/healthcheck.go:392 +0x246
github.com/youtube/vitess/go/vt/discovery.(*HealthCheckImpl).checkConn(0xc42022c280, 0xc4201d2840, 0xc4200feb80, 0x11)
	/usr/share/hubspot/jenkins-home/workspace/vitess-rpm/vitess-build/src/github.com/youtube/vitess/go/vt/discovery/healthcheck.go:372 +0x1b8
created by github.com/youtube/vitess/go/vt/discovery.(*HealthCheckImpl).AddTablet
```
Hostnames were obfuscated, and ignore the build env file paths in the stack. But the crux is that this error is never surfaced anywhere, so all one has to go on is the lack of a valid target tablet for their queries. The connection was retrying over and over with a 2ms backoff (default retry schedule), and would never have succeeded.

Is there any way we can surface issues like this? We are currently ignoring the error returned from `healthCheckConn.stream()`. Perhaps we can log it with the throttled logger.

**Comment by bbeaudreault** [comment]
The fix in my case once I saw the logline was to fix the `tablet_grpc_server_name` argument so it matched the certificate returned from vttablet.

**Comment by bbeaudreault** [comment]
@michael-berlin sougou said you might know about these codepaths

**Comment by michael-berlin** [comment]
Yes, this analysis sounds great. One questions first:

There should have been a delay in the connection retries. It should have been this code: https://github.com/youtube/vitess/blob/master/go/vt/discovery/healthcheck.go#L378

Did you see that?


Adding the thottled logging doesn't sound bad. The only "problem" is that this error does happen regularly e.g. when you restart vttablet. I think that would be fine though?

For now I've created https://github.com/youtube/vitess/pull/2762 which just sets the "LastError" field. I think with that the error should have shown up on the vtgate status page as well.

I think we could add throttled logging for all errors as well? Or maybe just dial errors?

**Comment by bbeaudreault** [comment]
@michael-berlin thanks for the PR! I did see the delay, but the default value is 2 milliseconds: https://github.com/youtube/vitess/blob/master/go/cmd/vtgate/vtgate.go#L31. Perhaps we should lower that while we're at it?

#2762 looks good. I think this would have been clear if it had showed up in the vtgate status page, even without logging. However, I do think in general vitess could stand to log a bit more (even if we utilize the debug log level -- if that's a thing in go). So I'd be in favor of logging too, and perhaps using a lower loglevel if possible.

**Comment by bbeaudreault** [comment]
Closing due to #2762

**Comment by michael-berlin** [comment]
Missing bits which I'll fix:
- add throttled logging
- add retries with exponential backoff

**Comment by kivikakk** [comment]
yo! I'm working through <kbd>Type: Bug</kbd> from the earliest and up. I'd love to take this one on board, but frankly I have no idea where to even begin with throttled logging.

I've hunted around the codebase a bit; `vitess/go/vt/logutil` looks like it might be a starting point?
