### ISSUE TITLE
Unexpected crash of vttablet when starting up if mysql socket not found

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#3330]
On startup vttablet crashes with this stack trace:
```
Starting vttablet for cell1-0000000300 from ./manage-vttablet
W1020 07:24:18.642762   58683 action_agent.go:684] Cannot get current mysql port, not checking it (will retry at healthcheck interval): net.Dial(/path/to/vtdataroot/vt_0000000300/mysql.sock) to local server failed: dial unix /path/to/vtdataroot/vt_0000000300/mysql.sock: connect: no such file or directory (errno 2002) (sqlstate HY000)
E1020 07:24:18.643068   58683 backup.go:759] No backup to restore on BackupStorage for directory keyspace/0. Starting up empty.
RestoreFromBackup failed: Can't restore backup: net.Dial(/path/to/vtdataroot/vt_0000000300/mysql.sock) to local server failed: dial unix /path/to/vtdataroot/vt_0000000300/mysql.sock: connect: no such file or directory (errno 2002) (sqlstate HY000)
F1020 07:24:18.643282   58683 action_agent.go:293] RestoreFromBackup failed: Can't restore backup: net.Dial(/path/to/vtdataroot/vt_0000000300/mysql.sock) to local server failed: dial unix /path/to/vtdataroot/vt_0000000300/mysql.sock: connect: no such file or directory (errno 2002) (sqlstate HY000)
goroutine 16 [running]:
github.com/youtube/vitess/vendor/github.com/golang/glog.stacks(0xc4202d7b00, 0xc420238280, 0x139, 0x26d)
        /path/to/go/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/youtube/vitess/vendor/github.com/golang/glog.(*loggingT).output(0x18aa0a0, 0xc400000003, 0xc4200beb00, 0x14d773f, 0xf, 0x125, 0x0)
        /path/to/go/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:720 +0x345
github.com/youtube/vitess/vendor/github.com/golang/glog.(*loggingT).printf(0x18aa0a0, 0x3, 0xf443b7, 0x1c, 0xc420717f98, 0x1, 0x1)
        /path/to/go/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/youtube/vitess/vendor/github.com/golang/glog.Fatalf(0xf443b7, 0x1c, 0xc420717f98, 0x1, 0x1)
        /path/to/go/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:1148 +0x67
github.com/youtube/vitess/go/vt/vttablet/tabletmanager.NewActionAgent.func3(0xc420122640, 0x7fc7c851f198, 0xc420018100)
        /path/to/go/src/github.com/youtube/vitess/go/vt/vttablet/tabletmanager/action_agent.go:293 +0x19f
created by github.com/youtube/vitess/go/vt/vttablet/tabletmanager.NewActionAgent
        /path/to/go/src/github.com/youtube/vitess/go/vt/vttablet/tabletmanager/action_agent.go:288 +0x886
```

Data has been anonymised a bit. Code is recent (yesterday). mysqld was not running but I don't expect vttablet to "crash" in this case. It's fine if it gives up and stops.

**Comment by sougou** [comment]
The crash looks intentional. If it can't restore from backup, then it's an unrecoverable error. So, it prefers to crash to let you know immediately that something is wrong.

But in your case, it shouldn't have reached this code path. I don't think you intended for vttablet to try and restore from a backup, right?
