### ISSUE TITLE
`No module named google.protobuf.internal` error when running make site_test 

### ISSUE THREAD

**Issue by zmagg** [youtube/vitess#3343]
I get this error in the logs when running `make site_test` off of a fresh build of Vitess at its current HEAD. I can successfully start a Vitess cluster (and do things with it), just `make site_test` doesn't pass.

```
Traceback (most recent call last):
  File "test/tabletmanager.py", line 29, in <module>
    import utils
  File "/vagrant/src/github.com/youtube/vitess/test/utils.py", line 49, in <module>
    from vtproto import topodata_pb2
  File "/vagrant/py-vtdb/vtproto/topodata_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal
```

I can share the entire test log if it's useful, but all tests but `local.keyrange` fail.

```
2017/10/23 19:04:07 ============================================================
2017/10/23 19:04:07 local.keyrange                          	PASS
2017/10/23 19:04:07 local.keyspace                          	FAIL (3 tries)
2017/10/23 19:04:07 local.mysqlctl                          	FAIL (3 tries)
2017/10/23 19:04:07 local.tabletmanager                     	FAIL (3 tries)
2017/10/23 19:04:07 local.tabletmanager_consul              	FAIL (3 tries)
2017/10/23 19:04:07 local.tabletmanager_etcd                	FAIL (3 tries)
2017/10/23 19:04:07 local.tabletmanager_etcd2               	FAIL (3 tries)
2017/10/23 19:04:07 local.vtgatev2                          	FAIL (3 tries)
2017/10/23 19:04:07 local.vtgatev2_l2vtgate                 	FAIL (3 tries)
```

**Comment by sougou** [comment]
This sounds like either grpc for python didn't get installed, or maybe your PYTHONPATH didn't get set. In my PYTHONPATH, I see: $VTROOT/dist/grpc/usr/local/lib/python2.7/site-packages. Can you check if you have it?

The site_test would be needed mainly if you plan to make contributions. But it may still be worth getting the tests running. That way, you can use that infrastructure for easy troubleshooting.

**Comment by zmagg** [comment]
Excellent! This fixed it, thank you! I'll set the PYTHONPATH explicitly inside our build & test scripts internally.

```
2017/10/24 22:02:57 ============================================================
2017/10/24 22:02:57 local.keyrange                          	PASS
2017/10/24 22:02:57 local.keyspace                          	PASS
2017/10/24 22:02:57 local.mysqlctl                          	PASS
2017/10/24 22:02:57 local.tabletmanager                     	PASS
2017/10/24 22:02:57 local.tabletmanager_consul              	PASS
2017/10/24 22:02:57 local.tabletmanager_etcd                	PASS
2017/10/24 22:02:57 local.tabletmanager_etcd2               	PASS
2017/10/24 22:02:57 local.vtgatev2                          	PASS
2017/10/24 22:02:57 local.vtgatev2_l2vtgate                 	PASS
2017/10/24 22:02:57 ============================================================
2017/10/24 22:02:57 9 PASSED, 0 FLAKY, 0 FAILED, 0 SKIPPED
```

(I'm getting set up to maybe make contributions if necessary. I work with Demmer at Slack (yes, another one of us! 😁 )).
