### ISSUE TITLE
Panic on vttablet init

### ISSUE THREAD

**Issue by derekperkins** [youtube/vitess#3523]
I'm using `mycnf-file`, and somehow this caused a nil pointer panic

```
+ eval exec /vt/bin/vttablet '-topo_implementation="etcd2"' '-topo_global_server_address="topology-client.vitess:2379"' -topo_global_root=/vitess/global -log_dir '"/vt/vtdataroot/tmp"' -mycnf-file /vt/config/mysql-default.cnf -alsologtostderr -port 15002 -grpc_port 16002 -service_map '"grpc-queryservice,grpc-tabletmanager,grpc-updatestream"' -tablet-path '"zone1-1015307700"' -tablet_dir /vtdataroot/tabletdata -tablet_hostname '"zone1-main-80-x-replica-0.vttablet"' -init_keyspace '"main"' -init_shard '"80-"' -init_tablet_type '"replica"' -health_check_interval '"5s"' -mysqlctl_socket '"/vt/vtdataroot/mysqlctl.sock"' -db-config-app-uname '"vt_app"' -db-config-app-dbname '"vt_main"' -db-config-app-charset '"utf8"' -db-config-dba-uname '"vt_dba"' -db-config-dba-dbname '"vt_main"' -db-config-dba-charset '"utf8"' -db-config-repl-uname '"vt_repl"' -db-config-repl-dbname '"vt_main"' -db-config-repl-charset '"utf8"' -db-config-filtered-uname '"vt_filtered"' -db-config-filtered-dbname '"vt_main"' -db-config-filtered-charset '"utf8"' -enable_semi_sync -enable_replication_reporter -orc_api_url '"http://orchestrator/api"' -orc_discover_interval '"5m"' -restore_from_backup -gcs_backup_storage_bucket -gcs_backup_storage_root -s3_backup_aws_region -s3_backup_storage_bucket -s3_backup_storage_root -s3_backup_server_side_encryption
++ exec /vt/bin/vttablet -topo_implementation=etcd2 -topo_global_server_address=topology-client.vitess:2379 -topo_global_root=/vitess/global -log_dir /vt/vtdataroot/tmp -mycnf-file /vt/config/mysql-default.cnf -alsologtostderr -port 15002 -grpc_port 16002 -service_map grpc-queryservice,grpc-tabletmanager,grpc-updatestream -tablet-path zone1-1015307700 -tablet_dir /vtdataroot/tabletdata -tablet_hostname zone1-main-80-x-replica-0.vttablet -init_keyspace main -init_shard 80- -init_tablet_type replica -health_check_interval 5s -mysqlctl_socket /vt/vtdataroot/mysqlctl.sock -db-config-app-uname vt_app -db-config-app-dbname vt_main -db-config-app-charset utf8 -db-config-dba-uname vt_dba -db-config-dba-dbname vt_main -db-config-dba-charset utf8 -db-config-repl-uname vt_repl -db-config-repl-dbname vt_main -db-config-repl-charset utf8 -db-config-filtered-uname vt_filtered -db-config-filtered-dbname vt_main -db-config-filtered-charset utf8 -enable_semi_sync -enable_replication_reporter -orc_api_url http://orchestrator/api -orc_discover_interval 5m -restore_from_backup -gcs_backup_storage_bucket -gcs_backup_storage_root -s3_backup_aws_region -s3_backup_storage_bucket -s3_backup_storage_root -s3_backup_server_side_encryption
I0103 20:37:34.346850       1 streamlog.go:122] Streaming logs from TabletServer at /debug/querylog.
I0103 20:37:34.348010       1 streamlog.go:122] Streaming logs from TxLog at /debug/txlog.
I0103 20:37:34.348134       1 mycnf_flag.go:128] No mycnf_server_id specified, using mycnf-file file /vt/config/mysql-default.cnf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xcaa9c1]
 goroutine 1 [running]:
main.main()
	/vt/src/github.com/youtube/vitess/go/cmd/vttablet/vttablet.go:87 +0x241
```

**Comment by enisoc** [comment]
This should be fixed by #3568.
